[WIP] auto fs backup in db repo base class
edrlab/thorium-reader pull request #1308
Opened 2021-01-08 22:22 UTC by panaC

2021-01-09 00:10 UTC, danielweck commented on src/main/db/repository/base.ts
> +        } catch (e) {
May I suggest adding a comment about `EXDEV`, as per:

https://github.com/sindresorhus/conf/blob/a96e9d78ac7e675a24ed702f1c21dd46a0b3ae0e/source/index.ts#L456-L468

2021-01-09 00:11 UTC, danielweck commented
For reference: I think this PR is successor or https://github.com/edrlab/thorium-reader/pull/1297

2021-01-11 10:44 UTC, panaC commented
What do you think @danielweck ?

2021-01-11 11:15 UTC, panaC commented
I think we have to add this to next release. the sooner the better. For the next db migration.

If you accepted this PR Daniel, of course :)

2021-02-16 08:30 UTC, danielweck requested changes
I've just fixed the unit tests (minor change, ad-hoc dependency injection container configuration).

I've just checked the generated JSON files, and of course, as we know, the "secrets" are stored in plain text. We need to ensure that LCP passphrases (SHA256) and OPDS authentication tokens + cookie jar are stored more securely.

2021-03-03 19:34 UTC, closed without merging