Migration remove edge case
edrlab/thorium-reader pull request #1452
Opened 2021-05-03 07:49 UTC by panaC

some db refactoring (remove try catch)

2021-05-04 06:51 UTC, danielweck commented
So, in this PR, OPDS and R2 Publications remain forever in the JSON "database" when they are removed / deleted by the user? If so, shouldn't we be concerned about unbounded growth?
PS: good idea tackling the issue of "automatic DB re-import when launching Thorium v1.7+" for both OPDS Publications and R2 Publications (I didn't try the OPDS scenario in my tests, but of course the problem exists here too).

2021-05-04 07:04 UTC, danielweck commented
PS - just nit-picking on wording: the bug we are trying to fix here is not an “edge / border case”, it is actually a very common and expected usage scenario. In a nutshell: Thorium automatically (attempts to) re-import deleted Publications and OPDS feeds from an existing SQLite / LevelDown database (because in v1.7+ the DB is immutable by design, as we want to enable v1.6 rollback ... whilst accepting that not all edge cases can be covered, such as the data of publications deleted in v1.7+ can not magically re-appear when moving back to v1.6). In the case of re-importing a removed Publication (all in v1.7+), this causes an observable failure in the UI due to missing UUID folder => red popup / slide-in notification which confuses the user. I am not sure how to deal with this problem for OPDS, but for Publications we could check the presence of the UUID folder, and skip the DB "absorb" phase for publications deemed corrupted.

2021-05-04 07:06 UTC, danielweck commented
Another interesting point is that even if we replace the entire publication/OPDS state data structure with a `removed` boolean (in order to minimize memory allocations), our current codebase doesn't check for UUID collisions (which, although extremely rare, can occur). We basically have no safeguard for verifying that an auto-generated ID isn't already in use, either in existing publications / OPDS feeds / bookmarks, etc. or in the `removed` map.

2021-05-04 08:24 UTC, panaC commented
> Another interesting point is that even if we replace the entire publication/OPDS state data structure with a `removed` boolean (in order to minimize memory allocations), our current codebase doesn't check for UUID collisions (which, although extremely rare, can occur). We basically have no safeguard for verifying that an auto-generated ID isn't already in use, either in existing publications / OPDS feeds / bookmarks, etc. or in the `removed` map.

With an uuid v4 the collision probability is ridiculously low. I think ! https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions

It's an interesting point , but for me currently not in our scope. Do you want investigate more on this point anyway ?

2021-05-04 08:26 UTC, panaC commented
> PS - just nit-picking on wording: the bug we are trying to fix here is not an “edge / border case”, it is actually a very common and expected usage scenario. In a nutshell: Thorium automatically (attempts to) re-import deleted Publications and OPDS feeds from an existing SQLite / LevelDown database (because in v1.7+ the DB is immutable by design, as we want to enable v1.6 rollback ... whilst accepting that not all edge cases can be covered, such as the data of publications deleted in v1.7+ can not magically re-appear when moving back to v1.6). In the case of re-importing a removed Publication (all in v1.7+), this causes an observable failure in the UI due to missing UUID folder => red popup / slide-in notification which confuses the user. I am not sure how to deal with this problem for OPDS, but for Publications we could check the presence of the UUID folder, and skip the DB "absorb" phase for publications deemed corrupted.

I'm totally agree with you , sorry for this bad title , I had no idea. I'm changing it

2021-05-04 08:34 UTC, panaC commented
> So, in this PR, OPDS and R2 Publications remain forever in the JSON "database" when they are removed / deleted by the user? If so, shouldn't we be concerned about unbounded growth?
> PS: good idea tackling the issue of "automatic DB re-import when launching Thorium v1.7+" for both OPDS Publications and R2 Publications (I didn't try the OPDS scenario in my tests, but of course the problem exists here too).

yes, it's the idea. There are never removed from json state. There are unbounded growth , I agree. however the publication document and opds-feed document is them under control. (the json size of each document is pretty small). I don't think it can have db bursting.

2021-05-04 09:10 UTC, danielweck commented
> With an uuid v4 the collision probability is ridiculously low. I think ! https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions
> 
> It's an interesting point , but for me currently not in our scope. Do you want investigate more on this point anyway ?

yep, let's address this in a separate development task / issue. this is a general problem, not spexific to this particular PR.

we use this uuid RFC v4 implementation: https://github.com/uuidjs/uuid/issues/420

2021-05-04 18:05 UTC, panaC commented
@danielweck let's merge it to deep test in develop branch.
what do you think ?

2021-05-07 06:53 UTC, danielweck requested changes
There are bugs in the `develop` implementation, and here too.

2021-05-07 07:37 UTC, danielweck commented
Just as I feared, the UUID is not automatically generated anymore for new PouchDB documents due to recent refactorings. For example an OPDS feed added in 1.7 has `identifier` = `DfDs1Rh2sTXRiCCec88B0` instead of `e77eb445-8d40-4551-b9cb-624b6c5bcf7a`. I'm working on this.

2021-05-07 08:31 UTC, danielweck commented
The CRC check for previously-deleted publications (but still in Redux state with "removed" flag) works fine, so the JSON DB now contains identical hashes, which is technically a breaking change but because this is an internal implementation detail we can proceed.

2021-05-07 09:46 UTC, danielweck commented
I tested the addition of bookmarks from 1.6 rollback, and expected import from 1.7 when launched once again (i.e. after an initial migration without any modifications to the publication, that is to say no `doNotMigrateAnymore` flag. This fails, in the sense that bookmarks created in 1.6 are not ported over to 1.7

2021-05-07 09:53 UTC, danielweck commented
One more point that should be addressed before merge: the unbounded DB growth should only be a problem with publications deleted from 1.7 that existed in 1.6 ... no need to preserve when pubs never existed in the native DB in the first place. I will implement a fix for this.

2021-05-13 10:39 UTC, danielweck commented on src/main/db/repository/opds.ts
> +                if (o && !o.removedButPreservedToAvoidReMigration) {
Correct, this is for safeguard consistency with usages of `store.getState().opds.catalog.find()` (i.e. direct catalog access, not via the `findAll()` variants)

2021-05-13 10:41 UTC, danielweck commented on src/main/db/repository/opds.ts
> +                // when the feed identifier is found (i.e. was successfully added) but the flag 'removedButPreservedToAvoidReMigration' is true
Logically this is non-sensical, because `save()` should never be called for removed publications. I am adding a code comment to clarify.

2021-05-14 09:14 UTC, merged