Fix/stealfocus
edrlab/thorium-reader pull request #2143
Opened 2024-05-06 13:54 UTC by panaC

fixes #2123

2024-05-06 14:15 UTC, panaC commented
complete and finish PR https://github.com/edrlab/thorium-reader/pull/2117

2024-05-06 18:11 UTC, danielweck requested changes

2024-05-07 11:44 UTC, panaC commented on src/renderer/reader/components/ReaderMenu.tsx
> +            }, 1000);
e29520dcceb98752bc3c556787cc07aec562dee9

2024-05-07 11:44 UTC, panaC commented on src/renderer/reader/components/ReaderHeader.tsx
> +                            >
e29520dcceb98752bc3c556787cc07aec562dee9

2024-05-07 12:27 UTC, panaC commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
Partially fixed with this commit https://github.com/edrlab/thorium-reader/pull/2143/commits/f9c0ddd861a55d57d8c0affaa15a2474d23d365f

2024-05-07 12:33 UTC, panaC commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
On not docked mode (fully dialog modal) : SHIFT + ALT + CLIC on an hyperlink doesn't close the modal. You must then click on the cross or hit escape key to close the modal, the focus isn't prevented to move to the trigger

2024-05-07 12:35 UTC, panaC commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
we can do the reverse in docked mode : aka SHIFT + ALT + CLIC on an hyperlink close the docked dialog and focus back to the main area @danielweck

2024-05-07 12:35 UTC, panaC commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
https://github.com/edrlab/thorium-reader/blob/f9c0ddd861a55d57d8c0affaa15a2474d23d365f/src/renderer/reader/components/ReaderMenu.tsx#L146-L150

2024-05-07 14:48 UTC, danielweck commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
Confirmed it was SHIFT + ALT in 2.4

https://github.com/edrlab/thorium-reader/blob/v2.4.1/src/renderer/reader/components/ReaderMenu.tsx#L251-L267

2024-05-07 14:48 UTC, danielweck commented on src/renderer/reader/components/ReaderHeader.tsx
> +                                    if (open) {
Note: also for ENTER key activation of TOC hyperlink (or bookmark, etc.) not just mouse click

2024-05-14 09:11 UTC, danielweck commented
Hello @panaC I propose that we merge this PR and later iterate on the subtle keyboard-driven navigation (SHIFT ALT CLICK on link or with ENTER key, for example). This PR branch has a code conflict, could you resolve it please? (I am not sure how to myself, you know the impacted code chunk better since you implemented the mods in the first place ... I don't want to break something :)

2024-05-14 11:21 UTC, panaC commented
> Hello @panaC I propose that we merge this PR and later iterate on the subtle keyboard-driven navigation (SHIFT ALT CLICK on link or with ENTER key, for example). This PR branch has a code conflict, could you resolve it please? (I am not sure how to myself, you know the impacted code chunk better since you implemented the mods in the first place ... I don't want to break something :)

Great, This is what i was going to do !

2024-05-14 11:29 UTC, merged